### ISSUE TITLE
RFE: Add Windspeed

### ISSUE THREAD

**Issue by stacksjb** [sbsrouteur/weewx-opensensemap#1]
Hello,

I also would like to report windspeed - is this a simple matter of creating another section and adding the appropriate sensor id?

**Comment by sbsrouteur** [comment]
Yes it is as simple as that.
You need to restart weewx after adding the sensors for them to be picked up and sent to opensensemap.

**Comment by sbsrouteur** [comment]
Hi,

Did you get it working ?
