### ISSUE TITLE
Sensor variables for weewx.conf

### ISSUE THREAD

**Issue by SanwebGit** [sbsrouteur/weewx-opensensemap#2]
Hello,

in the example it shown only to sensor variables for the weewx.conf:
[[[[outTemp]]]] & [[[[outHumidity]]]]

but where can i find the other variables for the other sensors for PM10, PM 2,5 ?

**Comment by sbsrouteur** [comment]
These variables are provided by the PM sensor plugin to weewx. Their names should be documented in the weewx plugin.

For my own PM sensor, (a sds011), sensors' names are hardcoded as : 

- pm2_5 
- pm10_0 
 
in the weewx plugin.
